version: "3.8"

services:

  ms-membership:
    build: ./ms-membership
    container_name: ms-membership
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  ms-product:
    build: ./ms-product
    container_name: ms-product
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - ms-membership

  ms-order:
    build: ./ms-order
    container_name: ms-order
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - ms-membership
      - ms-product

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
